### ISSUE TITLE
Naming confusion

### ISSUE THREAD

**Issue by josdejong** [oslabs-beta/SvelteStorm#54]
I just read about "SvelteStorm", nice initiative!

I have to say I was confused at first: based on the name I expected "SvelteStorm" to be the Svelte variant of IDE's of [Jetbrains](https://www.jetbrains.com/products/) (they have "WebStorm" and "PhpStorm" amonst others, language specific variations of the same IDE). 

I think it would be good to not have this confusion. People will have certain expectations because of this, and mismatching expectations will give frustrations and confusion. Please consider renaming this IDE.

**Comment by vfonic** [comment]
You're also risking Jetbrains filing a potential lawsuit or sending you a cease and desist letter.

**Comment by trasherdk** [comment]
Unless Jetbrains already have a product named `SvelteStorm` they are out of luck.
They could of course start attacking other products named `Something Storm` but they would be up against some experienced opponents.

[Apache Storm](https://storm.apache.org/)  is a free and open source distributed realtime computation system.
[Storm](https://storm-lang.org/) is a programming language platform with a strong focus on extensibility.

Personally I like the name `SvelteStorm` and see no reason to change.
