### ISSUE TITLE
What does "Clone this SvelteStorm 5.0 repo to your code editor of choice (VS Code works best)" mean?

### ISSUE THREAD

**Issue by shinokada** [oslabs-beta/SvelteStorm#86]
I'm not sure what "Clone this SvelteStorm 5.0 repo to your code editor of choice (VS Code works best)" means.

I can clone the repo, but how to clone it to VScode?

**Comment by elliottburr** [comment]
Hi Shinichi,

You can clone this repo to your local machine. From you machine's terminal, or the terminal in your code editor (VSCode), you can run `npm i` and `npm start` to launch SvelteStorm. Hope this helps!
